### ISSUE TITLE
Exit animation not executed

### ISSUE THREAD

**Issue by JesusTheHun** [timolins/react-hot-toast#100]
On your website I can see a nice default animation for custom components.
For some reason, in my case, the exit animation is not executed. The component stalls for the duration of the animation, and then just disappear.

Here is a repro : https://stackblitz.com/edit/react-ts-ck3qkp?file=index.tsx

**Comment by timolins** [comment]
When using `toast.custom()` no entry or exit animations are applied, to leave room for full customization.

You can style the default `ToastBar` instead of going fully custom, if you want to preserve that.

The TailwindCSS example on the website (as well as the example you provided) has a switch between the `animate-enter` and `animate-exit`. Those animations are not included in TailwindCSS by default and are declared in the sites [tailwind.config.js](https://github.com/timolins/react-hot-toast/blob/main/site/tailwind.config.js#L26).
