### ISSUE TITLE
v2.3.0-beta build is not esm compliant

### ISSUE THREAD

**Issue by sachinraja** [timolins/react-hot-toast#204]
In the new v2.3.0-beta build, `outExtension` was overridden with the build format:
https://github.com/timolins/react-hot-toast/blob/39c1bdac9ff3d8e17c2e65288717cf4fcb19a501/tsup.config.ts#L9-L13

This is not compliant with esm. tsup emits with the `.mjs` extension by default because packages with `"type": "commonjs"` (all packages implicitly have this) must use the `.mjs` extension for esm files according to Node's resolution. Bundlers may be more forgiving.

**Comment by timolins** [comment]
Interesting, thanks for pointing this out.

I introduced this overwrite because `size-limit` had problems importing the `.mjs` file. This no longer seems to be a problem after updating to the [latest version](https://github.com/ai/size-limit/tree/main/packages/preset-small-lib), which uses esbuild instead of webpack.

Nonetheless, it's somewhat concerning that some tools can't handle `.mjs` by default.

I found [this article](https://www.sensedeep.com/blog/posts/2021/how-to-create-single-source-npm-module.html) which also points to this problem. 

Do you have thoughts on this? I'd love to do this in an ESM compliant way, without compromising on support for commonly used build setups. 

---
[Preact](https://github.com/preactjs/preact/blob/master/package.json#L14-L18) seems to export both (`.esm.js` & `.mjs`).

**Comment by sachinraja** [comment]
> I found [this article](https://www.sensedeep.com/blog/posts/2021/how-to-create-single-source-npm-module.html#the-problem-with-mjs) which also points to this problem.

That article doesn't suggest a good practice btw.

Just to provide some qualification here, [I added ESM support to `react-query`](https://github.com/TanStack/query/pull/3521).

> Nonetheless, it's somewhat concerning that some tools can't handle .mjs by default.

I don't try to support these older tools. Instead, I just force them to use cjs.

> [Preact](https://github.com/preactjs/preact/blob/master/package.json#L14-L18) seems to export both (.esm.js & .mjs).

Preact has a bigger interest here since they want to have the smallest size possible, even for older bundlers.

Bundlers that support `"exports"` typically also support esm/.mjs. The tradeoff in implementing my solution here is that older bundlers/bundler versions will only get commonjs so there won't be any tree shaking. Mind if I do a PR to show you what I mean?

**Comment by timolins** [comment]
Thanks for your insights, interesting points.

> I really don't like these tools for that reason. To really get an overview of the size, you need to test with multiple bundlers.

You are right, they definitely don't tell you the whole story. I still like to use them, because they give me a feel what impact a PR has on bundle size. 

> I don't try to support these older tools. Instead, I just force them to use cjs.

Good point that old bundlers can use cjs as fallback. The problem with my size-limit example was, that I forced .mjs on it, which wouldn't happen if the bundler resolved it by itself.

> Mind if I do a PR to show you what I mean?

That'd be cool. I'm playing around with it as well. This is a snippet of the version I have right now. Is that what you envisioned? 

```json
  "main": "dist/index.js",
  "module": "dist/index.mjs",
  "types": "dist/index.d.ts",
  "exports": {
    "./package.json": "./package.json",
    ".": {
      "import": "./dist/index.mjs",
      "require": "./dist/index.js",
      "types": "./dist/index.d.ts"
    },
    "./headless": {
      "import": "./headless/index.mjs",
      "require": "./headless/index.js",
      "types": "./headless/index.d.ts"
    }
  }
```

**Comment by sachinraja** [comment]
Yes that's mostly right! But if you're using the `"types"` field in `"exports"` it needs to come first (see [TS docs](https://www.typescriptlang.org/docs/handbook/esm-node.html#packagejson-exports-imports-and-self-referencing)). Also the top level `"module"` field should be removed, it's a nonstandard one so it could break with the mjs extension.

**Comment by sachinraja** [comment]
Thanks @timolins! The new release looks good
