### ISSUE TITLE
Does not work with Preact

### ISSUE THREAD

**Issue by timuster** [timolins/react-hot-toast#27]
Hi, I was trying out the plugin and the basic 'Getting Started' code fails to launch the toast for me. 

I verified that the component renders properly, but it seems like the `toast` function is failing silently. Is there a way to turn on debug/error messages so that I can figure out what's going on? 

Here's the full code I used for reference:

```
import React from 'react';

import toast, { Toaster } from 'react-hot-toast';
const notify = () => toast('Here is your toast.');

const App = () => {
  return (
    <div>
      <button onClick={notify}>Make me a toast</button>
      <Toaster />
    </div>
  );
};

export default App;
```

**Comment by timuster** [comment]
I think the issue might be caused by some incompatibility with Preact (disabling `gatsby-plugin-preact` for me did the trick). Going to leave this issue open for now in case you guys would like to add support for Preact down the line. Good work btw! :)

**Comment by timolins** [comment]
Hi! You seem to be right, I can't get it to work with Preact either.

I created a Codesandbox that replicates this issue: https://codesandbox.io/s/react-hot-toast-preact-4qzgw?file=/components/app.js

It looks like the issue is related to the styling, which is done with [goober](https://github.com/cristianbote/goober).

React Hot Toast is using the React.createElement pragma, which is probably the root of the problem. I figured that preact-compat might solve this, but it seems like this isn't the case.
https://github.com/timolins/react-hot-toast/blob/7e4391db1908ff0168bacd87beda115408b76ce0/src/components/toaster.tsx#L8-L10

Maybe @cristianbote has some insights on this?

**Comment by cristianbote** [comment]
Hey @timolins! Thanks for the ping!.

Yikes 🤔 this is odd. Let me take a closer look at what's happening here. I'll report back.

**Comment by cristianbote** [comment]
Alrighty, so it boils down to how preact handles the render and hooks calls, in a single pass, batched. That's why the `height: 0` cause the bounding client rect basically evaluates a dom reference that has not yet been attached.

A quick and painless fix could be to wrap the `getBoundingClientRect` call in a `setTimeout` call.
https://github.com/timolins/react-hot-toast/blob/bcd52dbf930eb77f21559ddffac50610000744bc/src/components/toast-bar.tsx#L104-L105

would be:
```js
setTimeout(() =>
   const boundingRect = el.getBoundingClientRect(); 
   props.onHeight(boundingRect.height); 
 );
 ```
 
 Test it out on the main website 😃  seems to be working fine.

**Comment by timolins** [comment]
Thank you so much Cristian for figuring this out. Also, sorry for pointing fingers at goober at first. 🙃

**Comment by cristianbote** [comment]
😃 happy I could lend a hand! Oh, it's no problem, that's how we grow 💪.

**Comment by vixalien** [comment]
does not work with preact on deno:

```
error: Uncaught (in promise) ReferenceError: document is not defined
    at j (https://esm.sh/v96/goober@2.1.11/deno/goober.js:2:113)
    at Object.h (https://esm.sh/v96/goober@2.1.11/deno/goober.js:2:1765)
    at https://esm.sh/v96/react-hot-toast@2.4.0/deno/react-hot-toast.js:2:3753
```
