### ISSUE TITLE
Example of Custom Promise Toast?

### ISSUE THREAD

**Issue by lsbyerley** [timolins/react-hot-toast#67]
Is it possible to create a custom promise toast? I'd like to add a Dismiss button to all the toasts so I am using the custom toast mentioned in the documentation. However, when it comes to a custom promise toast, doesn't the `promiseFunc()` passed in to the promise toast take the place of the custom toast function?

**Comment by shshaw** [comment]
Also looking for a way to dismiss a Promise Toast. `message.promise` returns a `Promise`, not the id like the other toast methods.

**Comment by RomanFausek** [comment]
This would be awesome to have in documentation if possible. cc @timolins

**Comment by RomanFausek** [comment]
Anyway if it helps someone. I did something like this:

```
import React from 'react';
import toast from 'react-hot-toast';
import { v4 as uuid } from 'uuid';

import type { ToastProps } from './toast';
import { Toast } from './toast';

export const triggerToast = (
  title: string,
  settings?: SettingsType,
) => {
  toast.custom(
    t => (
      <Toast
        title={title}
        isError={settings?.isError}
        isLoading={settings?.isLoading}
        action={settings?.action}
        ariaRole={settings?.ariaRole}
        onClose={() => toast.dismiss(t.id)}
        isVisible={t.visible}
      />
    ),
    { id: settings?.id },
  );
};

triggerToast.promise = async <T,>(promise: Promise<T>) => {
  const id = uuid();

  triggerToast('Loading', { isLoading: true, id });

  promise
    .then(p => {
      triggerToast('success', {
        id,
      });

      return p;
    })
    .catch(() => {
      triggerToast('error', {
        id,
        isError: true,
      });
    });

  return promise;
};

```

**Comment by timolins** [comment]
Yes, this is possible. Let me explain how `toast.promise` works internally, so it's easier to understand how we are going to style it.

Compared to other toast types (success, error etc.), **toast.promise doesn't have its own toast type**.
It's just a helper function that creates a `toast.loading()` toast and updates the toast based on the provided promise.

You read the internals yourself her:  https://github.com/timolins/react-hot-toast/blob/main/src/core/toast.ts#L62-L91

In order to style `toast.promise()`, we need to style all toast types that are being dispatched by it. Meaning `loading`, `success` & `error`.

For small tweaks, I'd suggest using the [styling API](https://react-hot-toast.com/docs/styling).
For a full customisation, you can write your [own renderer](https://react-hot-toast.com/docs/version-2#custom-renderer-api).

Here is an example with custom notifications built with react-hot-toast + goober (styled-components like). This method works equally well with other styling methods.

Code-sandbox: https://codesandbox.io/s/react-hot-toast-custom-toasts-with-styled-components-i4xj6?file=/src/App.js

**Comment by lihsai0** [comment]
Just a reminder, the internals of `toast.promise` link could be with commit hash like this for better:

https://github.com/timolins/react-hot-toast/blob/f339d7105c90e64bc80ee836b987f2efe235035c/src/core/toast.ts#L110-L157
