### ISSUE TITLE
Question: do you plan to add HIDE button option in the toast ? And progress bar ?

### ISSUE THREAD

**Issue by Aarbel** [timolins/react-hot-toast#69]
![image](https://user-images.githubusercontent.com/25119847/115408208-fa63ce80-a1f0-11eb-9312-3fa8fdcc930f.png)

![image](https://user-images.githubusercontent.com/25119847/115408527-37c85c00-a1f1-11eb-8db1-7e20746f4475.png)

![image](https://user-images.githubusercontent.com/25119847/115409429-0a2fe280-a1f2-11eb-94d8-e9b4dfa53191.png)

Things like that would be awesome, do you plan to allow us to add it (maybe thru an option / react node) ?

**Comment by timolins** [comment]
I'm planning to add a dismiss mechanism in the future. Not sure about the progress bar yet. In the meanwhile it's possible to add render a your own close button, see the JSX example on the website.

It should also be possible to render your own progress bar based on that.

Closing due to duplicate:
#6 - Progress Bar
#7 - Hide Button

**Comment by Aarbel** [comment]
@timolins dismiss mechanism is really important for toasters to help users know easily that they can hide them.
