### ISSUE TITLE
Export `Toast` type

### ISSUE THREAD

**Issue by ohueter** [timolins/react-hot-toast#91]
It would be great if the `Toast` type was exported from the library.

I'm using toast with a function argument like this (simplified example):

```ts
import toast, { Toast /* error, not exported */ } from "react-hot-toast";

const Message = (message: string, t: any /* this cannot be typed, should be `t: Toast` */) => (
  <>
    <div>{message}</div>
    <CloseButton onClick={() => toast.dismiss(t.id)} />
  </>
);

toast.success((t) => Message(message, t))
```

which is not possible in TypeScript due to the missing export. In fact, I would appreciate exporting all types declared in `types.d.ts` :-)

**Comment by kephail** [comment]
I would also appreciate this.

**Comment by sachinraja** [comment]
Just saying, you can import `Toast` from `react-hot-toast/dist/core/types`. But it would be nice for it to be exported from `react-hot-toast`.

**Comment by jrmyio** [comment]
> Just saying, you can import `Toast` from `react-hot-toast/dist/core/types`. But it would be nice for it to be exported from `react-hot-toast`.

This works , however if "importsNotUsedAsValues": "error" is set in tsconfig.json, this will throw an error on `import { CSSProperties } from 'react';`:
`This import is never used as a value and must use 'import type' because 'importsNotUsedAsValues' is set to 'error'.ts(1371)`

I guess thats because the types file is imported directly.

On a side-note, would also be great to have access to `Renderable` type.
